apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-ingestion-service
  labels:
    app: data-ingestion
spec:
  replicas: 1
  selector:
    matchLabels:
      app: data-ingestion
  template:
    metadata:
      labels:
        app: data-ingestion
    spec:
      containers:
      - name: data-ingestion-service
        image: data-ingestion-service:4
        imagePullPolicy: IfNotPresent
        env:
        - name: KAFKA_BROKER
          value: "kafka:9092"  # Match your Kafka service name in Minikube
        ports:
        - containerPort: 5000
