apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasource
  labels:
    app: grafana
data:
  questdb.yml: |-
    # Content from your questdb.yml file
    apiVersion: 1
    datasources:
      - name: QuestDB
        type: postgres
        access: proxy
        url: questdb-service:8812  # Use QuestDB service name
        database: qdb
        user: admin
        password: quest
        jsonData:
          tlsSkipVerify: true
          queryTimeout: 60
          sslmode: 'disable'
        secureJsonData:
          password: quest